WITH BASE AS (
    SELECT *
      FROM {{ref('DIM_ATTRIBUTES')}}
)
SELECT DATE_WITNESS, 
    CASE WHEN 
        HAS_WEAPON AND 
        HAS_JACKET AND 
        NOT HAS_HAT
    THEN 'MATCH'
    ELSE 'NO MATCH'
    END AS ATTRIBUTE_MATCH 
  FROM BASE